
deploy:
  provider: gae
  keyfile: client-secret.json
  project: unitylearn-201416
  default: true
before_install:
- openssl aes-256-cbc -K $encrypted_26f673de2178_key -iv $encrypted_26f673de2178_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- gcloud config set project unitylearn-201416
