language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
before_install:
    - cd google-nodejs
before_script:
    - cd google-nodejs
script: 
    - npm install -g serverless
    - serverless deploy