language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
    - google-nodejs/node_modules
script: 
    - cd google-nodejs
    - npm install
    - npm install -g serverless
    - serverless deploy